### ISSUE TITLE
Doesn't work on Pixel 3 anymore

### ISSUE THREAD

**Issue by nhobson99** [huhao1987/NXloaderRB#3]
The latest update causes the injection to always fail. Short of installing an older version, I can't think of another way to make this work again. I can upload logs if needed, not sure of the steps though.

**Comment by huhao1987** [comment]
Strange, I didn't change the core codes, just add two pages. Does the old version work?

**Comment by huhao1987** [comment]
Close for no reply, it can be reopened when you want to discuss again.
